import assert from 'node:assert/strict';
import {copyFileSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync} from 'node:fs';
import {join} from 'node:path';

export function createReproductionDirectory(root) {
  // Template CI bounds /tmp to 2 GiB; clean compiler roots use ignored build storage.
  const storage = join(root, 'target');
  mkdirSync(storage, {recursive: true});
  assert.ok(lstatSync(storage).isDirectory(), 'reproduction storage must not be a symlink');
  return mkdtempSync(join(storage, 'foundry-reproduction-'));
}

export function copyRegularTree(source, destination) {
  const metadata = lstatSync(source);
  if (metadata.isFile()) {
    copyFileSync(source, destination);
  } else {
    assert.ok(metadata.isDirectory(), 'reproduction inputs must be regular files or directories');
    mkdirSync(destination);
    for (const name of readdirSync(source).sort()) {
      copyRegularTree(join(source, name), join(destination, name));
    }
  }
}

export function verifySameTree(left, right) {
  const first = lstatSync(left);
  const second = lstatSync(right);
  if (first.isFile()) {
    assert.ok(second.isFile(), 'reproduction output kind changed');
    assert.deepEqual(readFileSync(left), readFileSync(right), `different generated bytes: ${left}`);
  } else {
    assert.ok(first.isDirectory() && second.isDirectory(), 'nonregular reproduction output');
    const names = readdirSync(left).sort();
    assert.deepEqual(readdirSync(right).sort(), names, 'generated artifact closure changed');
    for (const name of names) verifySameTree(join(left, name), join(right, name));
  }
}
